// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuclcNeu9jzLKRrQVsQjNEnxADPOH4m1U',
    appId: '1:19979377370:web:cb0795cff88ddee45163e3',
    messagingSenderId: '19979377370',
    projectId: 'fir-testing-2-0',
    authDomain: 'fir-testing-2-0.firebaseapp.com',
    storageBucket: 'fir-testing-2-0.firebasestorage.app',
    measurementId: 'G-S426VHSBMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxiqt43TNM28z0UeBtiUo8EXV-Dw0Vrz8',
    appId: '1:19979377370:android:d4f2f136b63e355a5163e3',
    messagingSenderId: '19979377370',
    projectId: 'fir-testing-2-0',
    storageBucket: 'fir-testing-2-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2XTWGsruKY6NwwcmD12NTVPZ0p0tRIMA',
    appId: '1:19979377370:ios:2b03d1ef35bfef5c5163e3',
    messagingSenderId: '19979377370',
    projectId: 'fir-testing-2-0',
    storageBucket: 'fir-testing-2-0.firebasestorage.app',
    iosBundleId: 'com.example.firebase226',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2XTWGsruKY6NwwcmD12NTVPZ0p0tRIMA',
    appId: '1:19979377370:ios:2b03d1ef35bfef5c5163e3',
    messagingSenderId: '19979377370',
    projectId: 'fir-testing-2-0',
    storageBucket: 'fir-testing-2-0.firebasestorage.app',
    iosBundleId: 'com.example.firebase226',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuclcNeu9jzLKRrQVsQjNEnxADPOH4m1U',
    appId: '1:19979377370:web:c4a7116fa91f52395163e3',
    messagingSenderId: '19979377370',
    projectId: 'fir-testing-2-0',
    authDomain: 'fir-testing-2-0.firebaseapp.com',
    storageBucket: 'fir-testing-2-0.firebasestorage.app',
    measurementId: 'G-57Z4YV5XL3',
  );
}
